import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
// import "react-bootstrap";
import Header from "@/srccomponents/Header";
import Footer from "@/srccomponents/Footer";
import 'bootstrap/dist/css/bootstrap.css'
import { getSession } from "./lib/session";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "2nd Leg",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {

  const session = await getSession();
  const user = session?.user;


  return (
    <html lang="en">
        <body className={inter.className}>
        <Header user={user}/>
          {/* <Header /> */}
          <main>{children}</main>
          {/* <Footer /> */}
        </body>
    </html>
  );
}
