import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/srccomponents/Header";
import Footer from "@/srccomponents/Footer";
import { getSession } from "./lib/session";

import 'bootstrap/dist/css/bootstrap.css'
import "../styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "2nd Leg",
  description: "Generated by create next app",
  icons: {icon: '/logo.jpeg'},
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {

  const session = await getSession();
  const user = session?.user;


  return (
    <html lang="en">
        <body className={inter.className}>
        <Header user={user}/>
          {/* <Header /> */}
          <main style={{ paddingTop: '70px' }}>{children}</main>
          <Footer />
        </body>
    </html>
  );
}
